config/routes.rb
Rails.application.routes.draw do

  resources :exosuits
  resources :multitools
  resources :ships
  resources :trade_commodities do
    collection { post :import}
  end

  resources :technologies do
    collection { post :import}
  end

  resources :multitool_upgrades do
    collection { post :import}
  end

  resources :exosuit_upgrades do
    collection { post :import}
  end

  resources :energys do
    collection { post :import}
  end

  resources :elements do
    collection { post :import}
  end

  resources :alloys do
    collection { post :import}
  end
  resources :ship_upgrades do
    collection { post :import}
  end

  root 'dashboards#home'

  get 'dashboards/home'
  get 'dashboards/all_info'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/alloy.rb
class Alloy < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Alloy.create! row.to_hash
    end
  end
end

app/models/element.rb
class Element < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Element.create! row.to_hash
    end
  end
end

app/models/energy.rb
class Energy < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Energy.create! row.to_hash
    end
  end
end

app/models/exosuit.rb
class Exosuit < ActiveRecord::Base
  belongs_to :user
  has_many :exosuit_upgrades
  accepts_nested_attributes_for :exosuit_upgrades
end

app/models/exosuit_upgrade.rb
class ExosuitUpgrade < ActiveRecord::Base
  belongs_to :exosuit
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ExosuitUpgrade.create! row.to_hash
    end
  end
end

app/models/multitool.rb
class Multitool < ActiveRecord::Base
  belongs_to :user
  has_many :multitool_upgrades
  accepts_nested_attributes_for :multitool_upgrades
end

app/models/multitool_upgrade.rb
class MultitoolUpgrade < ActiveRecord::Base
  belongs_to :multitool
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      MultitoolUpgrade.create! row.to_hash
    end
  end
end

app/models/ship.rb
class Ship < ActiveRecord::Base
  belongs_to :user
  has_many :ship_upgrades
  accepts_nested_attributes_for :ship_upgrades
end

app/models/ship_upgrade.rb
class ShipUpgrade < ActiveRecord::Base
  belongs_to :ship

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ShipUpgrade.create! row.to_hash
    end
  end
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Technology.create! row.to_hash
    end
  end
end

app/models/trade_commodity.rb
class TradeCommodity < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      TradeCommodity.create! row.to_hash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :ship
  has_one :multitool
  has_one :exosuit
  has_secure_password

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def home
    @alloys = Alloy.all
    @elements = Element.all
    @energys = Energy.all
    @exo_upgrades = ExosuitUpgrade.all
    @multitool_upgrades = MultitoolUpgrade.all
    @ship_upgrades = ShipUpgrade.all
    @technologies = Technology.all
    @trade_commodities = TradeCommodity.all
    if session[:user_id]
      @ship = Ship.find(session[:user_id])
      @exosuit = Exosuit.find(session[:user_id])
      @multitool = Multitool.find(session[:user_id])
    end
  end



  def all_info
    @alloys = Alloy.all
    @elements = Element.all
    @energys = Energy.all
    @exo_upgrades = ExosuitUpgrade.all
    @multitool_upgrades = MultitoolUpgrade.all
    @ship_upgrades = ShipUpgrade.all
    @technologies = Technology.all
    @trade_commodities = TradeCommodity.all
  end
end

app/helpers/alloys_helper.rb
module AlloysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/energys_helper.rb
module EnergysHelper
end

app/helpers/exosuits_helper.rb
module ExosuitsHelper
end

app/helpers/multitools_helper.rb
module MultitoolsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/dashboards/all_info.html.erb
<!-- charts of all info, possibly tabs , acordian?-->


<ul class="accordion-tabs-minimal">
  <li class="tab-header-and-content">
    <a href="#" class="tab-link is-active">Alloys</a>
    <div class="tab-content">
      <h1>Listing Alloys</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Base cost in store</th>
            <th>Recipe</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @alloys.each do |alloy| %>
            <tr>
              <td><%= alloy.name %></td>
              <td><%= alloy.base_cost %></td>
              <td><%= alloy.recipe %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Elements</a>
    <div class="tab-content">
      <h1>Listing Elements</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Base cost in store</th>
            <th>Where to find</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @elements.each do |element| %>
            <tr>
              <td><%= element.name %></td>
              <td><%= element.base_cost %></td>
              <td><%= element.recipe %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Energy</a>
    <div class="tab-content">
      <h1>Listing Energies</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Base cost in store</th>
            <th>Recipe</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @energys.each do |energy| %>
            <tr>
              <td><%= energy.name %></td>
              <td><%= energy.base_cost %></td>
              <td><%= energy.recipe %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
     </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Technology</a>
    <div class="tab-content">
      <h1>Listing Technologies</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Base cost in store</th>
            <th>Recipe</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @technologies.each do |technology| %>
            <tr>
              <td><%= technology.name %></td>
              <td><%= technology.base_cost %></td>
              <td><%= technology.recipe %></td>
    </tr>
          <% end %>
        </tbody>
      </table>
      </div>
        </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Trade Commodities</a>
    <div class="tab-content">
      <h1>Listing Trade Commodities</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Base cost in store</th>
            <th>Recipe</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @trade_commodities.each do |trade| %>
            <tr>
              <td><%= trade.name %></td>
              <td><%= trade.base_cost %></td>
              <td><%= trade.recipe %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
        </div>
  </li>
</ul>

app/views/dashboards/home.html.erb
<% if session[:user_id]%>

  <p><h2>Ship Name:</h2> <%= @ship.name %></p>

  <h4>Upgrades:</h4>
  <% @ship.ship_upgrades.each do |upgrade| %>
    <%= upgrade.name %>
  <% end %>

 <br />

  <p><h2>Exosuit Name:</h2><%= @exosuit.name %></p>

  <h4>Upgrades:</h4>
  <% @exosuit.exosuit_upgrades.each do |upgrade| %>
    <%= upgrade.name %>
  <% end %>
 <br />

  <p>  <h2>Multitool Name: </h2><%= @multitool.name %></p>
  <h4>Upgrades:</h4>
  <% @multitool.multitool_upgrades.each do |upgrade| %>
    <%= upgrade.name %>
  <% end %>

 <br />
  <p><%= link_to 'New Ship', new_ship_path %> | <%= link_to 'New Multitool', new_multitool_path %> | <%= link_to 'New Exosuit', new_exosuit_path %></p>
<% else %>
  <p>Please log in!</p>
<% end %>