config/routes.rb
Rails.application.routes.draw do

  resources :exosuits
  resources :multitools
  resources :ships
  resources :trade_commodities do
    collection { post :import}
  end

  resources :technologies do
    collection { post :import}
  end

  resources :multitool_upgrades do
    collection { post :import}
  end

  resources :exosuit_upgrades do
    collection { post :import}
  end

  resources :energys do
    collection { post :import}
  end

  resources :elements do
    collection { post :import}
  end

  resources :alloys do
    collection { post :import}
  end
  resources :ship_upgrades do
    collection { post :import}
  end

  root 'dashboards#home'

  get 'dashboards/home'
  get 'dashboards/all_info'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/alloy.rb
class Alloy < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Alloy.create! row.to_hash
    end
  end
end

app/models/element.rb
class Element < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Element.create! row.to_hash
    end
  end
end

app/models/energy.rb
class Energy < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Energy.create! row.to_hash
    end
  end
end

app/models/exosuit.rb
class Exosuit < ActiveRecord::Base
  belongs_to :user
  has_many :exosuit_upgrades
  accepts_nested_attributes_for :exosuit_upgrades
end

app/models/exosuit_upgrade.rb
class ExosuitUpgrade < ActiveRecord::Base
  belongs_to :exosuit
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ExosuitUpgrade.create! row.to_hash
    end
  end
end

app/models/multitool.rb
class Multitool < ActiveRecord::Base
  belongs_to :user
  has_many :multitool_upgrades
  accepts_nested_attributes_for :multitool_upgrades
end

app/models/multitool_upgrade.rb
class MultitoolUpgrade < ActiveRecord::Base
  belongs_to :multitool
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      MultitoolUpgrade.create! row.to_hash
    end
  end
end

app/models/ship.rb
class Ship < ActiveRecord::Base
  belongs_to :user
  has_many :ship_upgrades
  accepts_nested_attributes_for :ship_upgrades
end

app/models/ship_upgrade.rb
class ShipUpgrade < ActiveRecord::Base
  belongs_to :ship

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ShipUpgrade.create! row.to_hash
    end
  end
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Technology.create! row.to_hash
    end
  end
end

app/models/trade_commodity.rb
class TradeCommodity < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      TradeCommodity.create! row.to_hash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :ship
  has_one :multitool
  has_one :exosuit
  has_secure_password

end

app/controllers/exosuits_controller.rb
class ExosuitsController < ApplicationController
  before_action :set_exosuit, only: [:show, :edit, :update, :destroy]

  # GET /exosuits
  # GET /exosuits.json
  def index
    @exosuits = Exosuit.all
  end

  # GET /exosuits/1
  # GET /exosuits/1.json
  def show
  end

  # GET /exosuits/new
  def new
    @exosuit = Exosuit.new
    @exosuit.exosuit_upgrades.build
  end

  # GET /exosuits/1/edit
  def edit
    @exosuit.exosuit_upgrades.build
  end

  # POST /exosuits
  # POST /exosuits.json
  def create
    @exosuit = Exosuit.new(exosuit_params)

    respond_to do |format|
      if @exosuit.save
        format.html { redirect_to @exosuit, notice: 'Exosuit was successfully created.' }
        format.json { render :show, status: :created, location: @exosuit }
      else
        format.html { render :new }
        format.json { render json: @exosuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exosuits/1
  # PATCH/PUT /exosuits/1.json
  def update
    respond_to do |format|
      if @exosuit.update(exosuit_params)
        format.html { redirect_to @exosuit, notice: 'Exosuit was successfully updated.' }
        format.json { render :show, status: :ok, location: @exosuit }
      else
        format.html { render :edit }
        format.json { render json: @exosuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exosuits/1
  # DELETE /exosuits/1.json
  def destroy
    @exosuit.destroy
    respond_to do |format|
      format.html { redirect_to exosuits_url, notice: 'Exosuit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exosuit
      @exosuit = Exosuit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exosuit_params
      params.require(:exosuit).permit(:name, :user_id, exosuit_upgrades_attributes: [:name, :recipe, :category])
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
    @ship = Ship.new
    @ship.ship_upgrades.build
  end

  # GET /ships/1/edit
  def edit
    @ship.ship_upgrades.build
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :user_id, ship_upgrades_attributes:[:name, :recipe, :category])
    end
end

app/helpers/alloys_helper.rb
module AlloysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/energys_helper.rb
module EnergysHelper
end

app/helpers/exosuits_helper.rb
module ExosuitsHelper
end

app/helpers/multitools_helper.rb
module MultitoolsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/exosuits/_form.html.erb
<%= form_for(@exosuit) do |f| %>
  <% if @exosuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exosuit.errors.count, "error") %> prohibited this exosuit from being saved:</h2>

      <ul>
      <% @exosuit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>


  <%= f.fields_for :exosuit_upgrades do |ff| %>
  <h2>Edit upgrades</h2>
    <div>
      <div class="subfield">
        <%= ff.label :name %><br>
        <%= ff.text_field :name %>
      </div>
      <div class="subfield">
        <%= ff.label :recipe %><br>
        <%= ff.text_field :recipe %>
      </div>
      <div class="subfield">
        <%= ff.label :category %><br>
        <%= ff.text_field :category %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exosuits/edit.html.erb
<h1>Editing Exosuit</h1>

<%= render 'form' %>

<%= link_to 'Show', @exosuit %> |
<%= link_to 'Back', exosuits_path %>

app/views/exosuits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exosuits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exosuits.each do |exosuit| %>
      <tr>
        <td><%= exosuit.name %></td>
        <td><%= exosuit.user_id %></td>
        <td><%= link_to 'Show', exosuit %></td>
        <td><%= link_to 'Edit', edit_exosuit_path(exosuit) %></td>
        <td><%= link_to 'Destroy', exosuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exosuit', new_exosuit_path %>

app/views/exosuits/new.html.erb
<h1>New Exosuit</h1>

<%= render 'form' %>

<%= link_to 'Back', exosuits_path %>

app/views/exosuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exosuit.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @exosuit.user_id %>
</p>

<%= link_to 'Edit', edit_exosuit_path(@exosuit) %> |
<%= link_to 'Back', exosuits_path %>